name: Accessibility Check

on: [push, pull_request]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axe-core

      - name: Run accessibility tests
        run: |
          node -e "const axe = require('axe-core'); axe.run('http://localhost:3000', (err, results) => { if (err) throw err; console.log(results); });"
